version: '3'

services:
  threat_modeling_service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    restart: unless-stopped